name: crimson
description: Fast, efficient and easy-to-use JSON parser and serializer for Dart.
repository: https://github.com/simc/crimson
version: 0.4.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.0
  source_gen: ^1.4.0

dev_dependencies:
  test: ^1.24.4
  very_good_analysis: ^5.1.0
